services:
  frametv:
    build: .
    image: frametv-art-gallery:local
    container_name: frametv_artgallery
    restart: always
    ports:
      - "8999:8000"
    volumes:
      - frametv_data:/data
    environment:
      - SECRET_KEY=supersecretkey
      - FRAME_TV_DATA=/data

volumes:
  frametv_data:
